### ISSUE TITLE
Upload of big videos stalls

### ISSUE THREAD

**Issue by henkvantijen** [wireload/screenly-ose#123]
Upload of large videos, tried 300mb and later 140mb, results in a unresponsive system, and failed upload. 
enough space on sd card (8gb)

please allow for big files , upto 800 mb or 1gb.

**Comment by over64** [comment]
wait for https://github.com/wireload/screenly-ose/pull/317
Tested 1,3 GB file size. Upload speed avg ~500Kb/s. It's slow but it's restriction of Python WSGI platform.

**Comment by hixair** [comment]
Still have issues uploading 300-400mb mp4 files to a freshly installed rpi3. Smaller files upload and store fine !

**Comment by vpetersson** [comment]
@hixair did you use the development branch?

**Comment by hixair** [comment]
@vpetersson Yes, I used the link from the website to the latest release on GitHub. What is the best way to update to develop branch from the raspberry pi ?

**Comment by vpetersson** [comment]
@hixair That's the stable build. In order to upgrade to the development release you need to SSH into the box and run `./screenly/run_upgrade.sh` and select Yes to the question if you want to install the development release.

**Comment by hixair** [comment]
@vpetersson Thank you so much ! I will test this tomorrow and report !
