### ISSUE TITLE
On management page upload multiple images

### ISSUE THREAD

**Issue by iLLiac4** [wireload/screenly-ose#149]
Add the feature if possible:
On management page upload multiple images at once.

**Comment by waterloomatt** [comment]
Any progress here? Trying to create an electronic picture frame with hundreds of images. Thanks!

**Comment by vpetersson** [comment]
@waterloomatt It's scheduled for *Sprint 2*. You can see the milestones [here](https://github.com/wireload/screenly-ose/milestones).

**Comment by Lil-briX** [comment]
Is this feature still planed? 
I just wonder why u removed it from Sprint 2

**Comment by vpetersson** [comment]
I actually removed the sprint entirely as we're re-organizing a bit.

**Comment by Lil-briX** [comment]
So this feature is still on the TODO list? 
This feature and the "auth" Feature are the most important IMHO. 
And im looking forward to it! 
Good Job u all are doin' here! 
Im glad i found screenly :+1:

**Comment by over64** [comment]
How will we manage images, uploaded in batch mode? In single asset edit mode? (how it works now)

**Comment by vpetersson** [comment]
I'd say we skip the asset edit interface when we do batch uploads and simply assign the default properties to these. Then, the user can manually edit these.

**Comment by vpetersson** [comment]
Resolved in #561.
