### ISSUE TITLE
Feature Request - Remote Control

### ISSUE THREAD

**Issue by broswell** [wireload/screenly-ose#172]
We are using screenly-ose like a digital picture frame for our museum displays.  The bigger screens and higher resolution are terrific!

We miss the remote control when giving tours

Use a web browser on a cell phone like the remote control.  It should have
->  Skip forward to next asset
--   Hold at the current asset
<-- Go back to prior asset

We could think of a lot more enhancements (zoom, pan, etc) 

Happy to pay a bounty!

**Comment by vpetersson** [comment]
To be honest, it doesn't sound like a feature that makes sense in Screenly. It seems like a presentation software (LibreOffice perhaps) would be a better fit.
