### ISSUE TITLE
old asset is displayed until log in to config screen

### ISSUE THREAD

**Issue by magnets99** [wireload/screenly-ose#207]
bit of a weird one this:
When i turn on the pi's in the morning yesterdays asset is displayed until you log in into the config, then it immediately starts working again and the viewer log under system info gives the impression it was working all along.
But the actual image from yesterday is displayed. I think it may be something to do with the fact i turn the pi's off at night.

To reproduce:
make 2 images, we'll call them A and B
load them up into screenly with A showing until 11pm this evening. and B showing from 3am tomorrow. Switch them both on, A should move to the active section
turn your pi off via the cron command 
01 17 * * * sudo /sbin/shutdown -h now
in the morning of the next day (AFTER 3am) turn on your pi and let it load without going into the management screen

Observed behavior (bug)
Sceernly will load up and show asset A. once you log into the management screen it will start showing b before you change anything

Expected Behavior
that a stops showing and b becomes active once ntp sync is complete.

notes:
tried on two different pi's, all pi's have access to local ntp server. Problem remains after at least 3 hours. all assets are images.

**Comment by vpetersson** [comment]
@magnets99 Are you able to reproduce this on the latest version?

**Comment by madcackler** [comment]
I've been running into this myself, and after the update I was still getting same behavior.

**Comment by vpetersson** [comment]
@madcackler Interesting.

Could you run the following and attach the file here?

```
$ cd ~/screenly
$ export PYTHONPATH=$(pwd)
$ python lib/diagnostics.py > ~/diagnostics.json 
```

Once done, could you attach the file here? That should help us troubleshoot the issue.

**Comment by magnets99** [comment]
Hi Viktor,
I havn't seen it in a while, i'm running the new version but in the end I modified the hardware setup and just have the rpi powered up 24/7.
So to answer your question: No, but i'm using a workaround.

just cathcing up on the other comments. The pi does access a NTP server on our internal lan.

**Comment by vpetersson** [comment]
@magnets99 Got it. Yeah I would recommend running the device 24/7 regardless. Closing out issue.

**Comment by denniskho** [comment]
Dear sir,
I also have same issue, how to solve this?
i already update and upgrade and run bash <(curl -sL https://www.screenlyapp.com/install-ose.sh)
problem still persist.
please advise.
Thanks

**Comment by magnets99** [comment]
hi Dennis,
the problem recently came back to me, different cause but same symptom. It was a power supply that over the course of 24hours would eventually brown out and do strange things to the pi. Changing the power supply fixed all my issues.
