### ISSUE TITLE
how can I disable ----   file:///tmp/screenly_html/black_page.html

### ISSUE THREAD

**Issue by fenix687** [wireload/screenly-ose#217]
Is there a way to make the video loop with out going to black between the video assets? so it is seamless?  I have also noticed that this happens between any video asset even if it is not the same one.

Thu, 28 Aug 2014 08:46:34 Showing asset Announcement_Loop_2014-08-23_V2-RSPsd.mp4 (video)
Thu, 28 Aug 2014 08:46:35 current url is file:///tmp/screenly_html/black_page.html
Thu, 28 Aug 2014 08:56:13 Showing asset Announcement_Loop_2014-08-23_V2-RSPsd.mp4 (video)
Thu, 28 Aug 2014 08:56:15 current url is file:///tmp/screenly_html/black_page.html
Thu, 28 Aug 2014 09:05:53 Showing asset Announcement_Loop_2014-08-23_V2-RSPsd.mp4 (video)

**Comment by skipperut** [comment]
Was curious as to if any progress had been made on being able to turn off the delay between the transition of video and the next asset.  Currently, there's about a 4-6 second delay from when the video ends and the next asset begins.  I tried the method that @dericcrago used, but ran into mixed results with other assets loading in the background of the video asset.

**Comment by armbrust80** [comment]
Hello
Is there a way to disable the black page.html, as this is loaded one second longer than the video?
Or can I add in this file, an image, which is then always shown?

**Comment by vpetersson** [comment]
No you can't really disable it, as that would break things.

**Comment by armbrust80** [comment]
But why must be showed the black screen one second longer, that's annoying.

**Comment by vpetersson** [comment]
That's probably while the next asset is loading. Keep in mind that the Raspberry Pi has its limitations. It's not a desktop computer. Loading assets can take some time.

**Comment by armbrust80** [comment]
That would be a solution, but this black screen appears after the video and not in front of the video.
For example: Video - black screen - image - video - black screen - image

**Comment by vpetersson** [comment]
The black screen can never appear in front of the video. That's technically impossible in the current solution as `omxplayer` renders to framebuffer, which will be rendered in front of the X11 session.

**Comment by vpetersson** [comment]
We've made a fair number of changes in the recent releases. My guess is that this went away. Please upgrade and let us know. Will re-open if we can reproduce the issue.
