### ISSUE TITLE
Not keeping asset order 

### ISSUE THREAD

**Issue by tengil** [wireload/screenly-ose#229]
The order of active assets sometimes changes when activating or deactivating other assets. Actually when activating/deactivating an asset all assets shuffle back to their initial positions.

Also, somewhat related, when activating an asset it's sometimes added to the bottom, sometimes to the top, sometimes in between.

**Comment by over64** [comment]
wait for https://github.com/wireload/screenly-ose/pull/319

**Comment by vpetersson** [comment]
Now works in master.
