### ISSUE TITLE
Display Time Needed

### ISSUE THREAD

**Issue by cabsports** [wireload/screenly-ose#239]
Hi There,

We are using Screenly OSE for our Menu Boards with in our club but have come across an enhancement that would be fantastic if it could be implemented.

We have one menu board for day time (9am to 5pm) and then one evenings (5pm to midnight).  At the moment there is no way to setup the display in advance so it would be great to add a display time with in the Active date & time that is already in the system

Example:
Menu Board 1: 
Active Date & Time: 01/Nov/2014 00:00 to 30/Nov/2014 23:59
Display Time: 09:00 to 17:00

Menu Board 2: 
Active Date & Time: 01/Nov/2014 00:00 to 30/Nov/2014 23:59
Display Time: 17:00 to 23:59

I hope I have posted this in the correct area.

Thanks
Duncan

**Comment by PeacefulRuler** [comment]
+1 on this feature. It would definitely be nice.

Thanks for this great software.
Fred

**Comment by lenny76** [comment]
+1

**Comment by danbsfc** [comment]
+1 for this. Something that would certainly be a welcome addition to OSE if possible?

Thanks

Dan

**Comment by cabsports** [comment]
Hi @vpetersson,

Just wondering if any thought has been given to adding this to Screenly OSE yet?

Thanks
Duncan
