### ISSUE TITLE
Error if file name contains French Character

### ISSUE THREAD

**Issue by cooljai** [wireload/screenly-ose#243]
Tried to upload a video and got the below error "You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings". Googled and found this connected to UTF-8. My filename contained the term "bibliothèque". Replaced the "è" with "e" and i was able to upload the video. Has anyone had similar experiences, and how can this be fixed?

**Comment by tiptronic** [comment]
Same thing happens, if the asset description contains any umlaut-characters (äöüß, etc)

**Comment by vpetersson** [comment]
@tiptronic Can you try pulling down the latest changes and see if that solves it?

**Comment by tiptronic** [comment]
@vpetersson I can confirm - this works now! 

Thanks!

Btw: 
- Why can't I link an asset from the file-system? (e.g. '/home/pi/stuff/image.png')?
- Why can't I add an WebPage using the file-protocol? (e.g. 'file:///home/pi/stuff/index.html')

**Comment by vpetersson** [comment]
Re your question: partially because we never got around to add that, but perhaps more importantly because of the security implications.

**Comment by tiptronic** [comment]
One more thing - after the update, the settings are no longer read/written to '~/screenly/misc/screenly.conf'

**Comment by tiptronic** [comment]
sorry - my bad: it's now in ''~/.screenly/screenly.conf'' (seems my docs are outdated - but what is the one in 'misc' good for?? ;))

**Comment by vpetersson** [comment]
`~/.screenly/screenly.conf` is the correct path. I has been that all along.

> but what is the one in 'misc' good for?

That includes various scripts and config files used during the installation.
