### ISSUE TITLE
Adding a local asset while Internet is unavailable

### ISSUE THREAD

**Issue by JBowness** [wireload/screenly-ose#247]
It appears as though uploading a new asset doesn't "take" if an Internet connection is unavailable.

To test this, I disconnected the WAN port on the router and uploaded an image file from my local machine.  It shows up on the ACTIVE ASSETS, but in the viewer logs, the playlist keeps showing as empty.

Tue, 30 Dec 2014 20:33:25 Generating asset-list...
Tue, 30 Dec 2014 20:33:25 Playlist is empty. Sleeping for 5 seconds
...
Tue, 30 Dec 2014 20:34:15 Playlist is empty. Sleeping for 5 seconds
Tue, 30 Dec 2014 20:34:20 Playlist is empty. Sleeping for 5 seconds

It seems I need to reestablish the Internet connection and reboot the Pi before it starts to play the local asset.

**Comment by over64** [comment]
It seems that duplicates https://github.com/wireload/screenly-ose/issues/228

**Comment by vpetersson** [comment]
@over64 so you're not able to reproduce this after applying PR #318?

**Comment by over64** [comment]
Simulated this situation via
```
pi@screenly ~ $ route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         gateway-local.i 0.0.0.0         UG    0      0        0 eth0
10.13.37.0      *               255.255.255.0   U     0      0        0 eth0
pi@screenly ~ $ sudo route del default
pi@screenly ~ $ route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
10.13.37.0      *               255.255.255.0   U     0      0        0 eth0
pi@screenly ~ $ ping 8.8.8.8
connect: Network is unreachable
```
Works fine with local assets (even for just added). Tested https://github.com/wireload/screenly-ose/commit/fe950f641218644d14396dac060183b49e430c2c

**Comment by vpetersson** [comment]
Ok, yeah deleting the default gw is a reasonable test. If it still works after that, I'm a happy camper. @JBowness let us know if it's still an issue.

**Comment by vpetersson** [comment]
@over64, @blackrabt reported this issue in master. Could you try to reproduce it?
