### ISSUE TITLE
Kernel Update?

### ISSUE THREAD

**Issue by pyavdr** [wireload/screenly-ose#254]
12 months before, there was the latest kernel update for screenly-ose. Raspian included new drivers in the latest kernel 3.18. which can help to integrate new Wlan adapters. Is there a chance to update the screenly ose image?

THY

**Comment by vpetersson** [comment]
We actually use a frozen apt repository for the official images, which is also used by Screenly Pro. The reason for this is to make sure that there are no surprises. 

Upgrading this takes a fair amount of effort. We might do that down the road, but not in the immediate future.
