### ISSUE TITLE
Screenly adding 20s to set duration.

### ISSUE THREAD

**Issue by dtdickman** [wireload/screenly-ose#259]
Hi there,

I've just implemented Screenly OSE at work and we are having some issues with asset durations. It seems that no matter what time I set an asset to, an additional 20s is always added. 

The image below shows 2 active assets. For the purpose of illustrating my issue, one asset is set with a duration of 10s and the other to 2s. Without fail, the slide changes 20s after the set duration.

Is anyone else having this issue? 

![screen shot 2015-02-05 at 1 51 19 pm](https://cloud.githubusercontent.com/assets/5060112/6066856/410dccc2-ad3e-11e4-8cfb-a3388e480737.png)

**Comment by vpetersson** [comment]
Hmm that's odd. Some initial questions:

 * Are you running anything else on the device beyond Screenly? 
 * What kind of SD card are you using (class, brand, model)?

**Comment by dtdickman** [comment]
Actually I just resolved the issue by running a software update. Thanks for the quick reply!

**Comment by vpetersson** [comment]
Great!
