### ISSUE TITLE
Screenly not full screen

### ISSUE THREAD

**Issue by jmarkwick** [wireload/screenly-ose#265]
This isnt an over scan issue or the wrong image size being used. when i boot up the raspberry everything is full screen until i hit the screenly splash screen.
Even the splash screen is shown in the top left.
![img_3532](https://cloud.githubusercontent.com/assets/7235673/6245171/9f17e39c-b753-11e4-94d1-a6a62c54f85f.JPG)

**Comment by vpetersson** [comment]
Does this happen for both images and videos?

**Comment by jmarkwick** [comment]
Hello,
This only occurs when showing images. videos play fine.
I have however solved the issue by starting a fresh and installing a new image.
