### ISSUE TITLE
raspberry pi B

### ISSUE THREAD

**Issue by nypuma27** [wireload/screenly-ose#267]
I have been trying to get screenly up on a raspberry pi B. First I istalled the screenly os embedded in the raspbian.. My problem was no wireless support and the mouse and desktop will not show. so the i wiped it and installed raspain wheezy and the after set up I installed screenly ose via terminal. after a reboot screenly does not boot up. can anyone point me in the right direction?? Thanks you!

**Comment by vpetersson** [comment]
Yes. Please see #256.
