### ISSUE TITLE
Unable to add https:// assets

### ISSUE THREAD

**Issue by moodytractor** [wireload/screenly-ose#272]
We have tried twice now to get Screenly to display Wordpress blogs (https secure webpages) and have been unable to do so. Today we ran the latest Screenly update before trying again.

We installed the latest update then ran the command to enable SSL. Like last time, all this has resulted in is a blank screen and an inability to access the machine through either the :8080 ip address historically used to access the screenly OSE  or the :443 ip address suggested for using Screenly after running the SSL command.

Please advise how we might fix this problem. We only use the system for one screen and as a small junior school, we cannot afford the Pro edition.

**Comment by vpetersson** [comment]
There is some confusion here. SSL support for the server (i.e. how you access the management interface) with SSL in the viewer component. 

In any case, it appears as something went wrong with the installation then. Please post the logs from `/tmp/screenly*` as well as the output when running the command.

**Comment by moodytractor** [comment]
We don't have the miniSD adapter. Is there any way of accessing the log on the terminal itself? A command that can be written?

**Comment by vpetersson** [comment]
Yes, you can access the virtual terminal. However, if you're not familiar with Linux, I recommend you simply re-flash the SD card and merely run the upgrade (and not the SSL component).

**Comment by moodytractor** [comment]
[image: image1.JPG]



On 24 Mar 2015, at 15:55, Viktor Petersson <notifications@github.com> wrote:

Yes, you can access the virtual terminal. However, if you're not familiar
with Linux, I recommend you simply re-flash the SD card and merely run the
upgrade (and not the SSL component).

—
Reply to this email directly or view it on GitHub
<https://github.com/wireload/screenly-ose/issues/272#issuecomment-85572798>.

**Comment by moodytractor** [comment]
![img_0027](https://cloud.githubusercontent.com/assets/11633197/6806203/2784a9ee-d23f-11e4-88ba-3241f9b74670.JPG)

**Comment by moodytractor** [comment]
![img_0031](https://cloud.githubusercontent.com/assets/11633197/6806335/f8e1ecb8-d23f-11e4-90d0-fc2c8c802d14.JPG)

**Comment by over64** [comment]
tested https://github.com/wireload/screenly-ose/commit/0c6fec271f05dfe3874bfed25ef39453372e1907
on yandex.ru, google.com, twitter.com
works fine without any special settings

**Comment by vpetersson** [comment]
Hmm could maybe be an NTP related issues? In any case. Closing out this as unreproduceable then.
