### ISSUE TITLE
Alert when new Software Update is available?

### ISSUE THREAD

**Issue by danbsfc** [wireload/screenly-ose#273]
I am using Screenly OSE on 2 monitors at work and they are just perfect for what we need! One thing that would be nice is to somehow be informed via the UI 'Web' Interface whenever a new software/firmware update is available to download and install?

Is this possible? Also could it be executed from the browser or would we need to still do it via SSH?

Thanks

**Comment by vpetersson** [comment]
We already display that in the web interface. You will however need to run the upgrade over SSH.

**Comment by anaglyph** [comment]
It already does inform you of an 'Update Available'.

![image](https://cloud.githubusercontent.com/assets/2710473/6825752/99ba371c-d2f4-11e4-91c8-9f988f2b4e9f.png)

Automatic security updates and Screenly's central software management is available on the paid version, so is possible. http://www.screenlyapp.com/

**Comment by danbsfc** [comment]
Strange, i've never seen / had that?
