### ISSUE TITLE
Upgrade Fails

### ISSUE THREAD

**Issue by Cyberprog** [wireload/screenly-ose#277]
Hi All,

Getting the following when running the upgrade script;

pi@cf-screenly0 ~ $ ~/screenly/misc/run_upgrade.sh
bash: line 2: syntax error near unexpected token `newline'
bash: line 2: `<?xml version="1.0" encoding="utf-8"?>'

I'm guessing something wrong at the github end?

Cheers!

Alex.

**Comment by vpetersson** [comment]
I just tried and it works for me.

This is most likely caused by the ongoing [DDoS attack](https://status.github.com/) on Github.

**Comment by kpdillon** [comment]
I have run the upgrade an I still see a message that says Update available in the GUI.  Is that supposed to be there?  Also, where can I look to see what bugs were fixed?

**Comment by vpetersson** [comment]
This could actually also be related to the DDoS attack, since it depends on checking the commit hashes from Github.

That said, it does seem to work on the [demo site](http://ose.demo.screenlyapp.com/).

**Comment by Cyberprog** [comment]
I was able to get the update run this morning - so I wonder if it hit a cloudflare page or something similar that caused it to b0rk yesterday.

**Comment by vpetersson** [comment]
To my knowledge, Github isn't using Cloudflare, so that shouldn't interfere. In any case, glad you got it working.

**Comment by Cyberprog** [comment]
May have been something similar :)
