### ISSUE TITLE
No Video playing when network disconnected

### ISSUE THREAD

**Issue by McNeillChris9** [wireload/screenly-ose#280]
Hi Guys, 

This may be a miss-understanding on my part, but I was hoping that once I got the desired assets up and running that I could remove the network cable from my rPi and use screenly to just blindly play, however when I've no network cable connected I am just getting a blank (black) screen shown.

Is this something that's by-design or something that can be worked around etc? 

Thanks,
Chris

**Comment by vpetersson** [comment]
Hi Chris,

I think this is still a known issue. I haven't had a chance to test this to be honest.

**Comment by over64** [comment]
tested https://github.com/wireload/screenly-ose/commit/fe950f641218644d14396dac060183b49e430c2c version. Works fine
