### ISSUE TITLE
Solution to fix its Raspberry on a rear screen

### ISSUE THREAD

**Issue by forum6691** [wireload/screenly-ose#281]
Hi every one

I 've just installed my raspberry with screenly OSE on the rear of my 16 inches screen, in order to have an autonomous system with the video cables, rasberry and screen.
I create an allumiun support fixed with the VESA holes. It is very simply.

Look at the photographies attached to this post.
Enjoy screenly OSE.
Cyril

![20150419_160004](https://cloud.githubusercontent.com/assets/12150405/7367978/0ce37fb8-eda4-11e4-91d4-d77d7564c230.jpg)

![20150419_160043](https://cloud.githubusercontent.com/assets/12150405/7367994/2c70cd7c-eda4-11e4-93d0-52d228dbdea3.jpg)

![20150419_171247](https://cloud.githubusercontent.com/assets/12150405/7367996/3070186a-eda4-11e4-8fc1-1ed6bf039ab7.jpg)

**Comment by vpetersson** [comment]
Cool. There are also readily available VESA available here:
 * [Pibow VESA Mount](https://www.pi-supply.com/product/pibow-vesa-mount/)
 * [Adafruit VESA Mount for Raspberry Pi](https://www.pi-supply.com/product/adafruit-vesa-mount-raspberry-pi/)
