### ISSUE TITLE
Black stripes displayed on image assets

### ISSUE THREAD

**Issue by cyuste** [wireload/screenly-ose#282]
Hello,
Just checking if this is a design limitation or I'm doing something wrong...

I've downloaded 2015-02-25-Screenly_OSE_4GB.img and installed it in my RB pi B+. I'm using a full HD TV.

Videos are displayed full-screen but images and web aren't: If the image resolution is lower than 1920x1080 screenly doesn't scale it (that's OK, I can live with that) but when the image is full HD (or even bigger) I can see a black stripe on the top and botton of the screen. In the top there's also a 1px line that crosses the screen, like about at 5% of the top of it. 

As a result, there are also black bands at the sides of the image, so in the end these contents look framed.

I can attach images if required, but I think it's quite easy to reproduce it.

Thanks,

**Comment by vpetersson** [comment]
This is a traditional overscan issue. The easiest way to fix this is to run `raspi-config` and change the overscan settings in there.
