### ISSUE TITLE
Server for OSE ?

### ISSUE THREAD

**Issue by eblumberg** [wireload/screenly-ose#288]
Hello,
I was just wondering if there would be an Enterprise level Server for the OSE player developed?  Many of your clients, including us, would rather own the server and host it on their own hardware.   I'm not asking for a FREE solution, we would gladly pay for it, but we don't want sensitive information on a cloud based system paying on a monthly basis for something we could pay for once, plus maybe a service contract or something.  

I love the Screenly OSE player, it's by far the best Raspberry Pi digital signage solution, but we need a server for it.

**Comment by vpetersson** [comment]
Hi there,

Thank you for the kind words.

Unfortunately we do not have any plans for launching a server model for OSE. I can see that there are certain use cases where an on-premise system is more desirable. However, it is a very different business model. 

The tech industry at large is moving toward subscriptions (e.g. OpEx vs. CapEx), and that seems to be resonating well with our customer base.
