### ISSUE TITLE
Add webpage authentication to assets

### ISSUE THREAD

**Issue by HIR3D** [wireload/screenly-ose#299]
Screenly works really well, but if I'm using FogBugz or JIRA and want to add a web-page asset, I essentially cannot do that without the ability to pass the user/password through in screenly. 

Am I missing something? 

Thanks for the help, and apologies if this is the wrong place for this.

**Comment by vpetersson** [comment]
Yeah, it's more or less not possible to do in a very clean/reliable way unless you're talking about Plain/Basic Auth. I'm not sure if it's possible to configure FogBugz/JIRA to use that, but I know that it isn't the default.

**Comment by HIR3D** [comment]
Bummer... Thanks for the response!
