### ISSUE TITLE
[Request] playback at specific time

### ISSUE THREAD

**Issue by Tsunayoshi** [wireload/screenly-ose#300]
Hello,

I am using the screenly ose for a public beamer. Therefor it would be nice to have the normal playlist, like it is now. But over that, a second playlist where you can define a specific time like, "every day at 10 o'clock play video X" and then resume the normal playlist after that.

I hope you can implement this in future version, it would be really nice.

**Comment by vpetersson** [comment]
This would require a fair amount of work. We don't support this in either OSE nor Pro right now, but it is something that we might add to Pro down the road. It is unlikely that we'll add it to OSE however given the complexity.
