### ISSUE TITLE
No sound output HDMI  after update?

### ISSUE THREAD

**Issue by mtijerino78** [wireload/screenly-ose#311]
Hello, 
I have this issue, when update a newly installation of screenly ose with 
$ ~/screenly/misc/run_upgrade.sh  
and reboot only 3.5 mm sound output works

somebody can help me fix this?

thanks

**Comment by vpetersson** [comment]
This is unlikely related to the update. There is a setting for this. in `~/.screenly/screenly.conf, which should also be exposed in the web interface.

**Comment by vpetersson** [comment]
@mtijerino78 Closing out this issue. Please comment if that didn't do the trick.
