### ISSUE TITLE
Google Slides doesn't update

### ISSUE THREAD

**Issue by surrealizations** [wireload/screenly-ose#314]
We are using Screenly OSE running on a RasPi 2 Model B to display a Google Slideshow on our lobby TV's. We have the slideshow published and added as a webpage asset to Screenly. The issue that we are having is when we update the slides, Screenly never loads the changes, just keeps displaying the previous slides.

I have tried adding the same webpage as a new asset and removing the previous one to force an update. The new asset will still play the old slides. It seems to require an entirely new link to be generated and uploaded as a new asset for it to pull a new webpage down.

This seems to me to be an issue with the website being cached on the Pi because the webpage that the asset refers to has changed online. Since the old slideshow will still play, the website that the new asset is loading must not be from the internet but local. If there was even a way to tell Screenly to re-download the website for each new asset, that would seemingly resolve the issue.

Short of creating a separate slideshow, publishing that and creating a new asset with that new link, I am not able to get the Screenly OSE to work for our use. Another option would of course be exporting our slideshow as a video and then uploading that as an asset each time we change it.

Thanks for the help, sorry if I've neglected to include important information.

**Comment by vpetersson** [comment]
Yes, this is a real bug. Added more details about it in #315. Closing out this one.
