### ISSUE TITLE
24 hr clock setting not applied

### ISSUE THREAD

**Issue by qbicdesign** [wireload/screenly-ose#333]
The 24hr clock feature seems to be broken. 
After turning it on, and clicking save, it reverts back to the off position, and the times remain in AM/PM format.

**Comment by mlott** [comment]
Just updated the latest version.  I'm getting the same problem.

**Comment by thorstenhartung** [comment]
Confirmed, same here

**Comment by xh3ni0n** [comment]
I used a workaround on CLI
simply edit ```~/.screenly/screenly.conf``` and set ```use_24_hour_clock = on```

**Comment by qbicdesign** [comment]
V cool. Thanks!

**Comment by Frankstar** [comment]
@xh3ni0n ty.
Cant find (yet) why its not working ..

**Comment by vpetersson** [comment]
Yeah I was able to reproduce this on the latest version.

**Comment by vpetersson** [comment]
Landed #365 which solves this issue. Thanks. @robberwick.
