### ISSUE TITLE
enabling 24 hour clock reverses date

### ISSUE THREAD

**Issue by qbicdesign** [wireload/screenly-ose#348]
I enabled 24hr clock mode in screenly.conf, but unfortunately this affects the date format too.
Once enabled the date appears in reverse format YYYY/MM/DD. Whilst understandable, its impossible to change the year, as whilst typing the new year the cursor skips to the end and you're unwittingly changing the day...  basically the date-picker can't handle the reverse date

**Comment by vpetersson** [comment]
Ah we had a similar issue in Screenly Pro. Will try to get this scheduled for a future spring.
