### ISSUE TITLE
Static IP for OSE?

### ISSUE THREAD

**Issue by WTPLJim** [wireload/screenly-ose#351]
Hello, 
Before I run the sudo nano /etc/network/interfaces at OS level on the Raspberry to change from DHCP to Static -- I just wanted to confirm that this will not interfere with the software.

I'm looking at installing a second Pi with Screenly and would like to provide each a static IP.

Thanks!

**Comment by vpetersson** [comment]
Yeah, you can configure it just as you would normally do. Screenly listens on `0.0.0.0:8080`, meaning that it will be accessible regardless of the IP configured.
