### ISSUE TITLE
Audio drop on first second of playback

### ISSUE THREAD

**Issue by mgrins2** [wireload/screenly-ose#353]
Hi there, 
A problem I have encountered is that the first second of audio in each video files seems to be missing on playback (when audio is output through HDMI). I'm looking at playing a lot of TV commercials and short videos which have audio right from the very start, so at the moment they sound cut off.

When played back through the analog 3.5mm jack the sound is good right from the start, so I'm pretty confidant it's an issue with my LG TV locking onto the HDMI audio, but could there be a way for screenly or omxplayer to provide a constant audio output so the TV isn't trying to constantly re-lock audio for each clip that is played?

**Comment by vpetersson** [comment]
Hi there,

There's no way to provide a constant audio stream in Screenly. The reason is simply that we don't have any background audio stream. It might possible to do something hackish by starting something with `aplay` in the background on loop.
