### ISSUE TITLE
PI hanging and rebooting after update

### ISSUE THREAD

**Issue by curtis45** [wireload/screenly-ose#359]
My pi 2B has been running great the last 6 months, then I decided to run an update 3 days ago and it hasn't been running right since.
It locks up and the screen goes black for roughly 5 min. randomly, then the pi restarts and goes for hours and then will lock up again.
this is screen shot of yesterday
![screenly error](https://cloud.githubusercontent.com/assets/17320377/13152499/5f3f8a90-d624-11e5-9f1c-80d34d89fd08.JPG)

this is a screenshot of this morning
![screenly error 2](https://cloud.githubusercontent.com/assets/17320377/13152536/8af067e0-d624-11e5-9179-ef8152cd18c9.JPG)

**Comment by vpetersson** [comment]
Try re-flashing the SD card with the disk image and run the upgrade again.

**Comment by curtis45** [comment]
wow, fast response, before I even had a chance to upload screen shots

**Comment by curtis45** [comment]
OK, formatted card, re-flashed with latested download of screenly, adjusted settings in raspi-config, updated screenly and loaded assets. ran for about an hour and completely locked up with no auto reboot, so I have no screen shot of logs.
Current running assets are 3 small videos and a webpage to here: http://www.wunderground.com/q/zmw:83530.1.99999 for weather.

**Comment by curtis45** [comment]
Webpage seems to be the problem, removed it and so far so good, would really like to get that back though.

**Comment by curtis45** [comment]
Well its not the webpage, locked up again about an hour after turning it off. :(

**Comment by curtis45** [comment]
OK,,,, I left only 1 mp4 video on over the weekend, it is 1 that I made from PowerPoint 2013. Worked perfectly all weekend. So my problem has to be another video I have been using, the only problem with that is that I have no new videos, so the update has a problem with some sort of video settings. I can post media info images if you want.

**Comment by curtis45** [comment]
Well it crashed again, but did restart on its own, this was looping only my video and the weather webpage.
![screenly error 3](https://cloud.githubusercontent.com/assets/17320377/13236032/a057baa2-d976-11e5-9ff6-e66bf90faba1.JPG)

**Comment by demethan** [comment]
To dev, might be related. Check issue #361  Thx

**Comment by curtis45** [comment]
Just to follow up demethan, I re-installed Screenly again and did not do the update. I put on everything I had before including the webpage and I am having no problems. There is definitely something wrong with the update.

**Comment by demethan** [comment]
I did the same. Flash the mSD card again with the img and everthing is fine if you don`t update.
