### ISSUE TITLE
Raspberry Pi 3 ready?

### ISSUE THREAD

**Issue by cellx** [wireload/screenly-ose#364]
Will this version work well with the newer Rapsberry Pi 3 too? Which configuration should I consider to use it?

**Comment by vpetersson** [comment]
You should be able to do the self-installed version on Wheezy. An updated version of the disk image will come later.

**Comment by bartvanraalte** [comment]
AFAIK there is no Wheezy available for the RPi3. The self-install script doesn't work on Jessie.

**Comment by vpetersson** [comment]
@bartvanraalte Yes, #368 will solve that.
