### ISSUE TITLE
Unable to show google calendar in Screenly - hosted via Dropbox

### ISSUE THREAD

**Issue by luedm** [wireload/screenly-ose#369]
after following this guide: https://www.screenlyapp.com/use-cases/dashboard/google-calendar/

I am unable to correctly display my calendar. I followed the instructions and included the embed url in a notepad file, changed the extension to .html, and uploaded and shared the link from Dropbox. 

When I share the link to the file, it simply shows the file, without launching it.

Does dropbox not allow these permissions anymore?

**Comment by vpetersson** [comment]
Yeah, we need to update that. Dropbox changed this recently and you can no longer serve HTML from there.

**Comment by luedm** [comment]
Does any other work around exist?

**Comment by vpetersson** [comment]
Sure, any web hosting service should do.

**Comment by vpetersson** [comment]
Try running the upgrade. This should hopefully have been fixed now.
