### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by mikeabrown09** [wireload/screenly-ose#381]
I added a link to this website http://mikesdevnet.com/ANN/Traffic/ and then all of a sudden I started to get Internal Server Error when going to settings.

**Comment by vpetersson** [comment]
Not sure why that is. Please post logs. That said, I can say that that page won't work anyways as it is using Flash.

**Comment by mikeabrown09** [comment]
Is there any workaround with the flash?

**Comment by mikeabrown09** [comment]
I can attempt to get th logs after work as this is at my house

**Comment by vpetersson** [comment]
> Is there any workaround with the flash?

No, not really. However, even if you did get the flash to load, it will most likely crash the Raspberry Pi from heavy load.
