### ISSUE TITLE
Uploads time out after 30 seconds

### ISSUE THREAD

**Issue by jscaptura** [wireload/screenly-ose#404]
Since the switch to gunicorn, uploads time out 30 seconds into the transfer on my system. Can this timeout be increased to allow larger assets to be uploaded?

**Comment by larsonholgers** [comment]
Is there any way to make the timeout variable adjustable in settings? When trying to upload video content of 70+ mb I get the timeout error consistently. Perhaps this is a bad idea but I just thought I'd throw it out there!
