### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by jhawk145** [wireload/screenly-ose#423]
When I link my companies website to the Asset, it will only give me a blank white screen. Is this some limitation of screenly based on the content of the website? This only occurs on this particular website for some reason.
Website is https://www.teslights.com

**Comment by vpetersson** [comment]
Well, that site doesn't work for me in Chrome either, so I reckon it's something wrong with the site.

**Comment by jhawk145** [comment]
Sorry about that. You are right. For some reason that one doesn't. This one should: http://teslights.com. Now when I use this link, it loads only part of the page,and loads very slowly,  and will not let me scroll.

**Comment by jhawk145** [comment]
Is there a reason everything is so slow? My guess would be how much Javascript is on the page.

**Comment by vpetersson** [comment]
Yeah, too much JavaScript and graphics.
