### ISSUE TITLE
Screenly OSE PHP and What Languages Supports

### ISSUE THREAD

**Issue by yasar9914** [wireload/screenly-ose#449]
Hi all, 

I was just trying to connect with mysql from screenly ose, but the php is not getting installed. Could you please suggest what is the best programming language to connect with database. Thanks in advance.

**Comment by vpetersson** [comment]
Screenly OSE is written in Python. The database used behind the scenes is SQLite. 

I'm not sure what you're looking to do, but if you want to extend the core of Screenly, you would have to do that in Python as we would not want to mix languages.

**Comment by yasar9914** [comment]
Thanks for your answer.

It was an idea that, my php page is not displaying in the browser. If it
successfully displayed, then probably I can connect with mysql database,
which allows me to change data n a real time within raspberry pi.

But php is not getting installed with screenly.

Will php get installed in screenly ?


On Wed, Jun 29, 2016 at 2:08 PM, Viktor Petersson <notifications@github.com>
wrote:

> Screenly OSE is written in Python. The database used behind the scenes is
> SQLite.
>
> I'm not sure what you're looking to do, but if you want to extend the core
> of Screenly, you would have to do that in Python as we would not want to
> mix languages.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/wireload/screenly-ose/issues/449#issuecomment-229293181>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATQ7JuFY5JzcBUvmwm3DCATpKgFUhS5yks5qQi8WgaJpZM4JAytX>
> .
>



-- 
Thanks & Regards,
yasar

**Comment by vpetersson** [comment]
While you could install PHP *on* the Raspberry Pi, I would strongly advice against it. Installing MySQL on the device would probably cause significant performance degradation. 

A better solution would be to simply host the PHP website somewhere else and simply add this as an asset to Screenly.

**Comment by yasar9914** [comment]
Yes Victor, I have understand. It would be really a great help.

My Last Question : So May I ask whether internet is a must to execute ?

On Wed, Jun 29, 2016 at 2:15 PM, Viktor Petersson <notifications@github.com>
wrote:

> While you could install PHP *on* the Raspberry Pi, I would strongly
> advice against it. Installing MySQL on the device would probably cause
> significant performance degradation.
>
> A better solution would be to simply host the PHP website somewhere else
> and simply add this as an asset to Screenly.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/wireload/screenly-ose/issues/449#issuecomment-229294759>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATQ7JnSSX9RZEIhLQpZBJmEzpiZ00ociks5qQjCZgaJpZM4JAytX>
> .
>



-- 
Thanks & Regards,
yasar

**Comment by vpetersson** [comment]
Normally, no. If the web server you're pointing to where the PHP app is running, then yes. If you have it on the same LAN, then no.
