### ISSUE TITLE
Change background color for static images?

### ISSUE THREAD

**Issue by EdwardsMike** [wireload/screenly-ose#455]
Hi! I've got a static image I wish to display that does not match the aspect ratio of 1920x1080 and when displayed, there is black background showing above and below the image. I can't seem to find the bit of code to change that from black to white (or any other color). Is it even possible?

**Comment by vpetersson** [comment]
It's currently not possible to change this, but you can edit [html_templates.py](https://github.com/wireload/screenly-ose/blob/master/html_templates.py) on your local system.
