### ISSUE TITLE
Assets when added are not being activated

### ISSUE THREAD

**Issue by vpetersson** [wireload/screenly-ose#460]
How to reproduce:

 * Remove all assets  and make sure the logs says 'Empty playlist'
 * Add new assets.
 * Activate the new assets.

**Behavior**: The assets are not being shown and the 'Empty playlist' message remains in the logs. You have to update the date and set it further in the past for the assets to show up.

**Expected behavior**: The new assets should show up.

**Comment by over64** [comment]
I cannot reproduce it now. Start date is 'current date' without any timezone related movements when I'm creating asset. Tested on Chrome & FF

**Comment by vpetersson** [comment]
Yup. I cannot reproduce this either anymore. Closing out.
