### ISSUE TITLE
Settings are not being applied without restart of viewer

### ISSUE THREAD

**Issue by vpetersson** [wireload/screenly-ose#461]
When doing the QA, I realized that settings (such as Audio output and Shuffle) only works after restarting the viewer service. These settings should be applied right away.

**Comment by over64** [comment]
Problem found. Server does not sends SIGUSR2 to viewer.
```systemctl kill --signal=SIGUSR2 screenly-viewer.service``` works fine

**Comment by vpetersson** [comment]
👍

**Comment by over64** [comment]
https://github.com/wireload/screenly-ose/pull/484
