### ISSUE TITLE
Playing Video Once

### ISSUE THREAD

**Issue by RajshekharHoratti** [wireload/screenly-ose#473]
How to make a video to play once and it should come back to inactive state

**Comment by vpetersson** [comment]
That is unfortunately not something that is supported.

**Comment by RajshekharHoratti** [comment]
Okiee thanks for the response. However, wanted to know if there's any API or trigger events from omxplayer to identify or detect end of video. All I figured out is viewer.py manages loading of assets.

**Comment by vpetersson** [comment]
The API docs are fairly sparse, but you can find some here:
https://github.com/wireload/screenly-ose/blob/master/docs/api.md
