### ISSUE TITLE
Webpage image rendering

### ISSUE THREAD

**Issue by firepro20** [wireload/screenly-ose#481]
I have a webpage running on Raspberry Pi 2 and latest screenly on an internal server. It is saved relative to the main page path.

When switching between webpages, there is a 1-2 sec rendering delay of the background image for the digital signage. Is this a limitation or is there a workaround?

**Comment by vpetersson** [comment]
This is most likely related to the Raspberry Pi resources. Not much we can do to speed that up  on our end unfortunately. Try making the web page less resource intense.
