### ISSUE TITLE
Asset Not Playing

### ISSUE THREAD

**Issue by rsenio** [wireload/screenly-ose#490]
Same issue that was reported before (334). Scheduled asset is not playing unless I re-visit the web ui. At that point it kicks in and acts normal.

Friday, I scheduled a jpg to play starting Monday at 730am. Came in today at 8am, and saw that the asset wasn't playing on the screen. Used a PC to view the web ui and it started playing.

**Comment by vpetersson** [comment]
Can you reproduce this on the development branch?

**Comment by rsenio** [comment]
Yes, it does

**Comment by rsenio** [comment]
Don't suppose there is a time frame for this update/fix? It's not very convenient to schedule an asset that doesn't play without manual intervention

**Comment by Larceniii** [comment]
Yep, just ran across this bug myself, device is not viable for production with this bug.

**Comment by vpetersson** [comment]
@over64 are you able to reproduce this?

**Comment by rsenio** [comment]
again, same as https://github.com/wireload/screenly-ose/issues/334

**Comment by over64** [comment]
@vpetersson, will try to reproduce

**Comment by over64** [comment]
bug reproduced. It's some logic error in Scheduler

**Comment by rsenio** [comment]
Are we any closer to fixing this? This bug basically breaks the whole point of using the product.

**Comment by over64** [comment]
@rsenio, https://github.com/wireload/screenly-ose/pull/503/ Merged in master now. Now we are working on next production release

**Comment by karel1** [comment]
I am experiencing this on the OSE as well (latest dev.version). I have to reboot to see the added asset play. Is this the same bug?

**Comment by vpetersson** [comment]
@karel1 can you provide precise steps on how to reproduce this? Then @over64 can take a look and see if he can reproduce it on his and (and subsequently fix it).

**Comment by karel1** [comment]
Thanks for your fast response. I tried to get the log files with "journalctl -f screenly\*" (starting in ~),  but response is "No journal files were found." Testing today I can not reproduce the error yet. So that is good! (?)

**Comment by rsenio** [comment]
This is fixed in the update I see waiting for an install?

**Comment by vpetersson** [comment]
@rsenio This was scheduled for [Sprint 2](https://github.com/wireload/screenly-ose/milestone/4?closed=1).

**Comment by over64** [comment]
@rsenio, bug you opened (scheduling assets in future) already fixed in master and in production branch too. You could upgrade or download new image.

**Comment by rsenio** [comment]
The update totally wiped out /etc/network/interfaces on both my Pi's

The file states "Generated by Screenly Network Manager". Where is this network manager and if I edit the interfaces file will it be overwritten again?

**Comment by over64** [comment]
@rsenio, it's not bug. It's network configurator which was migrated from PRO. You need to create
`/boot/network.ini`. Now use `/boot/network-sample.ini` as template.

**Comment by rsenio** [comment]
I've attempted that, seems super simple. But it's not working. My SSID is hidden, I assume that is the only thing that could keep this from functioning

**Comment by over64** [comment]
@rsenio, could you provide /etc/network/interfaces with wifi configuration, generated by screenly net manager?

**Comment by rsenio** [comment]
I have filled in the two lines of network.ini
[wlan0]
ssid=My SSID
passphrase=My wpa2 passphrase

The contents of /etc/network/interfaces after changing the above, and rebooting is

# Generated by Screenly Network Manager
auto lo
  iface lo inet loopback

auto wlan0
  iface wlan0 inet dhcp
  wireless-power off
  wpa-ssid "My SSID"
  wpa-psk "My wpa2 passphrase"

I'm missing the option(s) 
wpa-scan-ssid 1
wpa-ap-scan 1

**Comment by vpetersson** [comment]
Ah yes, this is something that we haven't ported to OSE yet. Closing out this ticket in favor of #518.

**Comment by over64** [comment]
@rsenio, for quick workaround you could disable `screenly-net-manager.service` right now and configure /etc/network/interfaces manual.
```
   cd /etc/systemd/system
   sudo systemctl enable screenly-net-manager.service
```

**Comment by rsenio** [comment]
Seriously? 

So now we've graduated from a massive schedule assets can't play bug, to a "oh we changed how the networking works, now your screwed until we fix the hidden SSID issue"

What am I supposed to do in the mean time, move to Yodeck?

**Comment by vpetersson** [comment]
@rsenio you can simply disable the network manager in the meantime.

**Comment by filipdc** [comment]
I have exactly the same issue as @rsenio  and can't seem to fix it.
can $ sudo systemctl disable screenly-net-manager.service solve this problem?
I don't get it.

**Comment by PhinPhin** [comment]
@rsenio I was like "Yodeck? *google*" though sadly that digital signage solution also needs onlineconnection. I wonder if it is really so f'cking hard to get something with a noob-backend that won't run in the cloud but on a Pi.... ridicules.

**Comment by vpetersson** [comment]
This might actually be related to the time of the device. The Raspberry Pi doesn't have an on-board RTC, so if it doesn't have any internet connection, it will not know what time it is. As such, you need to reconfigure the NTP server to point to a local NTP server.
