### ISSUE TITLE
webserver in screenly

### ISSUE THREAD

**Issue by Lil-briX** [wireload/screenly-ose#499]
Hey, 

it's not a real issue just a short question. 
Wich webserver is used in screenly to realize the content management page wich is accessible thorugh the webbrowser? 

Kind regards.

**Comment by vpetersson** [comment]
Screenly is served using [Gunicorn](http://gunicorn.org/), which is running a [Bottle app](http://bottlepy.org/), which is a lightweight WSGI server.
