### ISSUE TITLE
screenly ose doesn't run all assets, viewer crashes

### ISSUE THREAD

**Issue by cortegedusage** [wireload/screenly-ose#502]
I was running Screenly as an digital signage on a raspberry 1
as this was really slow. I decided to upgrade it for a raspberry 3
But now it won't play more then 2 or three assets, just plain jpg.
I've used a new sd card the same I've used before on an osmc installation
and I've added a good 2amp powersupply

in the log there seem to be some errors.

many thanks
Dennis van Paassen

Log:
screenly-viewer.service - Screenly Viewer
Loaded: loaded (/etc/systemd/system/screenly-viewer.service; enabled)
Active: active (running) since Fri 2016-10-21 19:46:31 CEST; 25s ago
Process: 814 ExecStartPost=/bin/rm -f /tmp/screenly_html/\* (code=exited, status=0/SUCCESS)
Process: 811 ExecStartPost=/bin/rm -f /tmp/uzbl_\* (code=exited, status=0/SUCCESS)
Process: 806 ExecStartPre=/usr/bin/xset s noblank (code=exited, status=0/SUCCESS)
Process: 801 ExecStartPre=/usr/bin/xset -dpms (code=exited, status=0/SUCCESS)
Process: 798 ExecStartPre=/usr/bin/xset s off (code=exited, status=0/SUCCESS)
Main PID: 810 (python)
CGroup: /system.slice/screenly-viewer.service
├─810 /usr/bin/python /home/pi/screenly/viewer.py
├─824 uzbl-core --config=- --uri=file:///tmp/screenly_html/black_page.html --print-events --connect-socket /home/pi/.cache/uzbl/event_daemon
└─829 python /usr/bin/uzbl-event-manager -va start
Oct 21 19:46:31 raspberrypi systemd[1]: Started Screenly Viewer.
Oct 21 19:46:32 raspberrypi python[810]: Loading browser...
Oct 21 19:46:32 raspberrypi python[810]: Browser loading file:///tmp/screenly_html/black_page.html. Running as PID 824.
Oct 21 19:46:32 raspberrypi python[810]: Generating asset-list...
Oct 21 19:46:33 raspberrypi python[810]: Showing asset 1109_zvidal.jpg (image)
Oct 21 19:46:33 raspberrypi python[810]: Sleeping for 10
Oct 21 19:46:43 raspberrypi python[810]: Showing asset DM_johnny-lloyd.jpg (image)

**Comment by cortegedusage** [comment]
Hi,

I did a sudo journalctl -f 
and find out the viewer crashes 
i've atached the log... Hope you can find out what is causing it.
I'm trying to degrade it to the raspb1 setup which worked for now.

many thanks

[screenly_log.txt](https://github.com/wireload/screenly-ose/files/546005/screenly_log.txt)

**Comment by vpetersson** [comment]
`insufficient resources for operation` looks suspicious. What memory split are you using? Also, how big are those images?

**Comment by cortegedusage** [comment]
I'm using the screenly image from github
I can't seem to find gpu_mem in confit.txt
but setting it to 1024 doesn't resolve anything.

the pictures are somewhat between 122kb and 1980kb.

**Comment by cortegedusage** [comment]
resizing the pictures to aprox 200 kb seems to resolve the question
is there a maximum for picture size?
