### ISSUE TITLE
Question - Managing multiple raspberry pi's running screenly-ose

### ISSUE THREAD

**Issue by aristosv** [wireload/screenly-ose#507]
Hello

Can you please explain (or point me to documentation) how to manage multiple raspberry pi's running screenly-ose? I have see this in the README file, but no additional explanation. 
```
$ docker run --rm -ti \
  -p 8080:8080 \
  -v $(pwd):/home/pi/screenly \
  wireload/screenly-ose-server
```

**Comment by vpetersson** [comment]
You can't. Screenly OSE is limited to one device only. The Docker is for local development only.

If you want to manage multiple devices, you need [Screenly Pro](https://www.screenly.io/tour/).
