### ISSUE TITLE
Problems with animated gif

### ISSUE THREAD

**Issue by forum6691** [wireload/screenly-ose#509]
I try to display simple animated gif, but some pictures block the screenly. 
They just begin to show the animation and block all the following slides-show.

Is a known problem ? Is there a solution ?

**Comment by vpetersson** [comment]
I think it should work, but it depends on how you are viewing them. Are you adding it as an asset or is it part of a website?

**Comment by forum6691** [comment]
I add  it as an asset

**Comment by vpetersson** [comment]
Alright, yeah we might need to refactor the image playback code to make this work. The issue (i think) is that we are displaying images as background images to piggy back on some automatic resizing elements etc.. It's very likely that this is what prevents GIFs to be rendered properly.

**Comment by forum6691** [comment]
OK thanks victor
