### ISSUE TITLE
Web interface not working

### ISSUE THREAD

**Issue by sattinger** [wireload/screenly-ose#517]
Since this morning i can not access the web interface anymore. Restarting the Raspberry does not help. Network Connection is ok since i can login via SSH.

**Comment by vpetersson** [comment]
Try upgrading to the latest version and see if the issue remains.

**Comment by vpetersson** [comment]
Try upgrading to the latest version and see if you are able to reproduce the issue.

**Comment by sattinger** [comment]
Ok, thank you very much. An update fixed the issue.
