### ISSUE TITLE
Add support for hidden SSIDs

### ISSUE THREAD

**Issue by vpetersson** [wireload/screenly-ose#518]

**Comment by vpetersson** [comment]
@over64 Can you look over PR #519? Is that logging compatible?

**Comment by over64** [comment]
You may log into syslog, yes, it will works. But you may
 - keep latest version from PRO
 - reapply this patch https://github.com/wireload/screenly-ose/pull/486/commits/53cd4269148c848f4852de09431887b1fa186358 to screenly-net-mgr.py
 - profit

**Comment by vpetersson** [comment]
Nice one, @over64. Fixed and will merge.
