### ISSUE TITLE
etc/network/interfaces issue

### ISSUE THREAD

**Issue by sattinger** [wireload/screenly-ose#521]
etc/network/interfaces is overwriting itself every boot.
I also tried the steps described here to setup wifi which was not working for me: https://support.screenly.io/hc/en-us/articles/212107126-Can-I-use-a-WiFi-adapter-with-Screenly-Pro-
I want to disable the Screenly_Net_Mgr now but i don't know how.

**Comment by vpetersson** [comment]
Duplicate of #521.

**Comment by vpetersson** [comment]
Duplicate of #521.
