### ISSUE TITLE
network.ini not applied at start up

### ISSUE THREAD

**Issue by lamrod** [wireload/screenly-ose#522]
As part of the static network configuration a network.ini configuration file must be placed in the /boot partition.
During the boot process this file is supposed to be parsed and the configurations made.

This is not happening

**Comment by vpetersson** [comment]
Strange. I've accepted your PR. Does that solve the issue? Thanks for that btw.

**Comment by lamrod** [comment]
It has worked on the 3 devices we have running in our office.

**Comment by vpetersson** [comment]
Cool. Closing out. Thanks.

**Comment by lamrod** [comment]
I've just noticed that the Ansible role doesn't actually reference the file that I edited in my PR. Is this intended or have I just missed something?

**Comment by vpetersson** [comment]
Ah yes, that file is actually not in use. That's from the old system. It was replaced by [this](https://github.com/wireload/screenly-ose/blob/master/ansible/roles/network/files/screenly-net-manager.service) file. Let me delete this file to avoid confusion.

**Comment by vpetersson** [comment]
Resolved in #524. Just waiting for a LGTM from @over64 before merging.
