### ISSUE TITLE
Support Wifi connection with WPA-Enterprise

### ISSUE THREAD

**Issue by zaphod2010** [wireload/screenly-ose#547]
Looks like the Screenly Net Mgr setup currently does not support WPA-Enterprise. At least I did not find a way to configure this in /boot/network.ini

Okay - the workaround would be to disable the Screenly Net Mgr service and manually tweak /etc/network/interfaces

I am not a fan of having such proprietary config files. This is just an artificial limitation and wpa_supplicant.conf is way more powerful than this approach.

**Comment by vpetersson** [comment]
You're free to disable it. The reason why we have it is to simplify most configurations. WPA-Enterprise however, is not supported. It's also the way customers configure network in Screenly Pro, where they don't have access to the system.
