### ISSUE TITLE
Screenly realtime google analytics page

### ISSUE THREAD

**Issue by DorianPIERRE** [wireload/screenly-ose#549]
I try without success to display a google analytics page ... the active part of the page is white without content only the side menu
Is there any one who have try ?
Thanks a lot for your answer
Dorian

**Comment by vpetersson** [comment]
You can't display the regular Google Analytics page. You can try with something like [Geckoboard](https://www.geckoboard.com/), which can connect to your Google Analytics account and render the data in a more screen-friendly format.

**Comment by DorianPIERRE** [comment]
Thanks a lot ... I'll look about.
