### ISSUE TITLE
static ip address in network.ini

### ISSUE THREAD

**Issue by jassoo** [wireload/screenly-ose#550]
static ip address in network.ini wont work in OSE using latest ( 2016-12-01-Screenly_OSE_4GB )

**Comment by vpetersson** [comment]
Hi @jassoo, 

We're in the process of switching to our network configuration tool. You can read more about that [here](https://support.screenly.io/hc/en-us/articles/213678343-How-do-I-configure-a-Screenly-node-to-use-a-static-IP-). If you're having issues with this, I would suggest that you disable the Screenly network services and simply use `/etc/network/interfaces`.
