### ISSUE TITLE
QA Checklist - wrong link

### ISSUE THREAD

**Issue by cellx** [wireload/screenly-ose#564]
No 2:
https://www.screenly.io/latest-ose <- link not working

it should be https://www.screenly.io/ose/ or https://github.com/wireload/screenly-ose/releases

**Comment by vpetersson** [comment]
@cellx - Good catch. Where is this referenced?

**Comment by cellx** [comment]
https://github.com/wireload/screenly-ose

Quick links:

Support Forum
Screenly OSE Home
Live Demo
**QA Checklist <- this**

**Comment by vpetersson** [comment]
Ah, it was not in the code repo. That's why. Thanks and resolved.
