### ISSUE TITLE
Mute video in the playlist - request for additional feature

### ISSUE THREAD

**Issue by ppk4** [wireload/screenly-ose#569]
When I play a video I do not always want to listen to the video sound.

If I connect the screen thru hdmi, I can set the audio to the 3,5mm jack. I won't have to listen. But this setting is for all sound. I would like to have a choice.

Would it be possible at the setup of the asset to have a tic box for sound / no sound?

**Comment by vpetersson** [comment]
You mean on a per-asset level? If so, that's not something that I think we will implement. 

If you mean globally, you can simply just pick the option you're not using (i.e. set it to 3.5mm to disable sound over HDMI and vice versa).
