### ISSUE TITLE
sudo not included in docker build

### ISSUE THREAD

**Issue by btwq** [wireload/screenly-ose#570]
Here's an updated Dockerfile

Added in line 6: 

```
RUN apt-get update && \
    apt-get -y install git-core net-tools python-pip python-netifaces python-simplejson python-imaging python-dev sqlite3 libffi-dev libssl-dev && \
    apt-get install sudo && \     # I added this line to enable sudo commands
    apt-get clean

```
[Dockerfile.txt](https://github.com/wireload/screenly-ose/files/1049608/Dockerfile.txt)

**Comment by vpetersson** [comment]
See the comment in #571. This is not the purpose of the Docker container. I don't think there is any need for this in the Docker container.
