### ISSUE TITLE
Auto name completion fails when editing an existing asset

### ISSUE THREAD

**Issue by vpetersson** [wireload/screenly-ose#93]
How to reproduce:

 * Upload and save an asset without filling out a name
 * Bring up the editing dialogue
 * Delete the name and press save

The desired result is that the name will be the the same as when you uploaded the asset, but instead the name will be the full path of the asset (on disk).

**Comment by over64** [comment]
according to https://github.com/wireload/screenly-ose/pull/331

**Comment by vpetersson** [comment]
Not reproducible anymore.
